//go:build !ignore_autogenerated

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *NirvanaNodeClass) DeepCopyInto(out *NirvanaNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NirvanaNodeClass) DeepCopy() *NirvanaNodeClass {
	if in == nil {
		return nil
	}
	out := new(NirvanaNodeClass)
	in.DeepCopyInto(out)
	return out
}

func (in *NirvanaNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NirvanaNodeClassList) DeepCopyInto(out *NirvanaNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NirvanaNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NirvanaNodeClassList) DeepCopy() *NirvanaNodeClassList {
	if in == nil {
		return nil
	}
	out := new(NirvanaNodeClassList)
	in.DeepCopyInto(out)
	return out
}

func (in *NirvanaNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NirvanaNodeClassSpec) DeepCopyInto(out *NirvanaNodeClassSpec) {
	*out = *in
}

func (in *NirvanaNodeClassSpec) DeepCopy() *NirvanaNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(NirvanaNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NirvanaNodeClassStatus) DeepCopyInto(out *NirvanaNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		copy(*out, *in)
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]PoolStatus, len(*in))
		copy(*out, *in)
	}
}

func (in *PoolStatus) DeepCopyInto(out *PoolStatus) {
	*out = *in
}

func (in *PoolStatus) DeepCopy() *PoolStatus {
	if in == nil {
		return nil
	}
	out := new(PoolStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *NirvanaNodeClassStatus) DeepCopy() *NirvanaNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(NirvanaNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}
